apiVersion: environment.cloudbees.com/v1alpha1
kind: GitRepository
metadata:
  name: dshep-ci-pipeline-workshop-nov-insurance-frontend                             
  namespace: previews
spec:
  url: https://github.com/dshep-ci-pipeline-workshop-nov/insurance-frontend.git
  apiTokenSecretRef:
    name: beedemo-dev-github-token
  autoUpdateContexts:                           
  - default
